name: app_version_plus
description: A Flutter package for checking app version updates across Android, iOS, and Huawei app stores, with ready-to-use UI widgets and customizable functions.
version: 0.1.1
homepage: https://github.com/adampermana/app_version_plus
repository: https://github.com/adampermana/app_version_plus
issue_tracker: https://github.com/adampermana/app_version_plus/issues
topics: [version, app-update, apple, huawei, apkpure]
license: MIT

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  http: ^1.6.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.adampermana.app_version_plus
        pluginClass: AppVersionPlusPlugin
      ios:
        pluginClass: AppVersionPlusPlugin
      macos:
        pluginClass: AppVersionPlusPlugin
  assets:
    - assets/age_android/
    - assets/age_ios/
